name: Periodic Health Check

on:
  schedule:
    - cron:  '15 12 * * *'
jobs:
  daily_ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping
      run: echo "ping"
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://app-part-11.herokuapp.com
        max-attempts: 3
        retry-delay: 5s
